//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public int ConversationId { get; set; }
        public string Theme { get; set; }
    
        public virtual User Creator { get; set; }
    }
}
